export const _pubKey = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx1u1+yxmsEir8Omz6Va4
qqMXVchcBRHWAcIDRbpIU3FNHXGw5QrtG3W/gKSxAN5e+JPm2h6nV86bLIdPPmw5
1nZ0mqgu1isl6VAyoQOjZ+B8E+Th63LcrjuiLALPrJ2aqqzbRoytA1PMTNl2Te74
gg4jrn/a+A1sVFujhLkUlMlQRDEbeFeMIvvJ9icutjUdPW1uyLnLPSehbXMZnaXC
oB89r3fofHzXeaf3CULR0x/RvwuMihwpZZpoEtmnGJubQntW4zLzMhYW2jfkRLUb
sWeoeVaxNkGSxb3bbz7fF4ATlrCNZz/1HL8ASXqxEvBUMItddnSnuTBPNGB1FWIN
pQIDAQAB
-----END PUBLIC KEY-----`
